Do not require users to provide miss_track_file
Addressing:
Traceback (most recent call last):
  File "/misp_import.py", line 189, in <module>
    main()
  File "/misp_import.py", line 147, in main
    "miss_track_file": settings["MISP"]["miss_track_file"],
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 1257, in __getitem__
    raise KeyError(key)
KeyError: 'miss_track_file'